package skill

const codingStyleTemplate = `---
name: {{.Username}}-coding-style
description: Write code in {{.Username}}'s style - captures their naming conventions, code organization, error handling, testing patterns, and coding philosophy. Use when asked to write code like {{.Username}} or to emulate their coding approach.
---

# {{.Username}}'s Coding Style

This skill was auto-generated by Devlica from {{.Username}}'s GitHub activity.

## Coding Philosophy

{{.Philosophy}}

## Code Style Rules

{{.CodeStyle}}

## Testing Approach

{{.Testing}}

## Project Patterns

{{.ProjectPatterns}}

## Distinctive Traits

{{.Traits}}
`

const codeReviewerTemplate = `---
name: {{.Username}}-code-reviewer
description: Review code like {{.Username}} - captures their review priorities, feedback style, and what they look for in pull requests. Use when asked to review code as {{.Username}} or to emulate their review approach.
---

# {{.Username}}'s Code Review Style

This skill was auto-generated by Devlica from {{.Username}}'s GitHub activity.

## Review Priorities

{{.ReviewPriorities}}

## Feedback Style

{{.ReviewVoice}}

## Communication Patterns

{{.Communication}}

## Collaboration Style

{{.CollaborationStyle}}
`

const developerProfileTemplate = `---
name: {{.Username}}-developer-profile
description: Understand {{.Username}}'s developer identity - their interests, community engagement, and what drives them as an engineer. Use when you need context on what {{.Username}} cares about professionally.
---

# {{.Username}}'s Developer Profile

This skill was auto-generated by Devlica from {{.Username}}'s GitHub activity.

## Interests and Focus Areas

{{.DeveloperInterests}}

## Project Patterns

{{.ProjectPatterns}}

## Collaboration Style

{{.CollaborationStyle}}

## Distinctive Traits

{{.Traits}}
`
